src = $(wildcard *.md)

all:
	javac Frontend/Main.java && javac Backend/Main.java

clean:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \;

runfrontend:
	java Frontend.Main

runbackend:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \; && javac -cp sqlite.jar: Backend/Main.java && java -cp sqlite.jar: Backend.Main

debugf:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \; && javac Frontend/Main.java && java Frontend.Main