src = $(wildcard *.md)

all:
	javac Frontend/Main.java && javac Backend/Main.java

initfrontend: 
	javac Frontend/Main.java

initbackend:
	javac Backend/Main.java

clean:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \;

build:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \; && javac Frontend/Main.java && javac Backend/Main.java

runfrontend:
	java Frontend.Main

runbackend:
	java Backend.Main

debugf:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \; && javac Frontend/Main.java && java Frontend.Main