src = $(wildcard *.md)

all:
	javac Frontend/Main.java && javac Backend/Main.java

frontend: 
	javac Frontend/Main.java

backend:
	javac Backend/Main.java

clean:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \;

build:
	find  . -name  '*.class' -type  f -print -exec  rm -rf  {} \; && javac Frontend/Main.java && javac Backend/Main.java 